# Generated by Django 3.2.19 on 2023-06-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_file_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='file_attach',
        ),
    ]
