# Generated by Django 3.2.19 on 2023-05-23 18:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        # ('taggit', '0005_auto_20220424_2025'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        # migrations.AddField(
        #     model_name='product',
        #     name='tags',
        #     field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        # ),
    ]
